import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The lofi-node API reference under website/node-api-gen/ is generated by
// tools/api_docs.ts --node; ordering comes from the emitted sidebar_position
// frontmatter.
const sidebars: SidebarsConfig = {
  nodeApi: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
