import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The API reference under website/api-gen/ is generated by tools/api_docs.ts;
// ordering comes from the emitted sidebar_position frontmatter.
const sidebars: SidebarsConfig = {
  api: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
